/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example
import java.nio.file.Paths
import java.nio.file.Files

fun main() {
   // val currentDirFile = Paths.get("/src/main/kotlin/org/example/example.txt").toAbsolutePath().toString() 			
    val currentDirFile = Paths.get("src/main/kotlin/org/example/example.txt").toAbsolutePath() 			
    println(currentDirFile)
	val lines = Files.readAllLines(currentDirFile)
    lines.forEach { println(it) }
}
